begin;
select plan(10);
select has_type('public','cohort_status','cohort status exists');
select has_type('public','module_release_mode','release mode exists');
select has_table('public','cohorts','cohorts exist');
select has_table('public','cohort_modules','cohort modules exist');
select has_table('public','cohort_items','cohort items exist');
select has_table('public','cohort_module_items','cohort placements exist');
select has_table('public','cohort_item_resources','cohort resources exist');
select has_function('public','create_cohort_from_course',array['uuid','text','date','date','text'],'snapshot function exists');
select has_function('public','sync_course_item_to_cohorts',array['uuid','uuid[]'],'sync function exists');
select policies_are('public','cohorts',array['student reads accessible cohort','teacher manages own cohorts'],'cohort policies are explicit');
select * from finish();rollback;
