begin;
select plan(8);
select has_type('public','invitation_status','invitation status exists');
select has_type('public','enrollment_status','enrollment status exists');
select has_table('public','cohort_invitations','invitations exist');
select has_table('public','cohort_enrollments','enrollments exist');
select policies_are('public','cohort_invitations',array['teacher manages cohort invitations'],'invites are teacher-only');
select policies_are('public','cohort_enrollments',array['student reads own enrollment','teacher manages enrollments'],'enrollment policies are explicit');
select has_function('public','is_active_student_in_cohort',array['uuid'],'membership predicate exists');
select has_function('public','activate_cohort_invitation',array['uuid','uuid','text'],'atomic acceptance exists');
select * from finish();rollback;
